run:
  timeout: 2m

linters:
  disable-all: true
  enable:
    - dupl
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unused

linters-settings:
  dupl:
    threshold: 400
