version: "2"

run:
  timeout: 2m

formatters:
  enable:
    - gofumpt
    - goimports

linters:
  default: none
  enable:
    - dupl
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unused

  settings:
    dupl:
      threshold: 400
    revive:
      rules:
        - name: package-comments
          disabled: true
