# https://taskfile.dev

version: "3"

vars:
  BINDIR: bin
  BINNAME: uplift
  GIT_COMMIT:
    sh: git rev-parse HEAD
  GIT_SHA:
    sh: git rev-parse --short HEAD
  GIT_BRANCH:
    sh: git branch --show-current
  LDFLAGS: >
    -X github.com/gembaadvantage/uplift/internal/version.version=dev-{{.GIT_SHA}}
    -X github.com/gembaadvantage/uplift/internal/version.gitCommit={{.GIT_COMMIT}}
    -X github.com/gembaadvantage/uplift/internal/version.gitBranch={{.GIT_BRANCH}}
    -X github.com/gembaadvantage/uplift/internal/version.buildDate={{now | date "2006-01-02T15:04:05Z07:00"}}

tasks:
  default:
    desc: Runs all of the default tasks
    cmds:
      - task: clean
      - task: lint
      - task: docker-lint
      - task: test
      - task: build

  build:
    desc: Build the uplift binary
    cmds:
      - go build -ldflags '-s -w {{.LDFLAGS}}' -o '{{.BINDIR}}/{{.BINNAME}}' ./cmd/uplift

  test:
    desc: Run the tests
    cmds:
      - go test -race -vet=off -p 1 -covermode=atomic -coverprofile=coverage.out ./...

  lint:
    desc: Lint the code using golangci
    cmds:
      - golangci-lint run --timeout 5m0s

  docker-lint:
    desc: Lint the Dockerfile using Hadolint
    cmds:
      - hadolint Dockerfile

  fmt:
    desc: gofumpt all code
    cmds:
      - gofumpt -w -l .

  clean:
    desc: Remove any built artifacts
    cmds:
      - rm -rf {{.BINDIR}}
