# Copyright (c) 2021 Gemba Advantage
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# in the Software without restriction, including without limitation the rights
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - ga-paul-t
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report. Please be as descriptive and concise as possible. We value all input from the community.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what happened.
      placeholder: Tell us what happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce it
      description: Please list all of the steps taken to reproduce this bug.
      value: |
        1.
        2.
        3.
        ...
      render: shell
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Your uplift configuration
      description: If it is an issue related to your configuration file, please paste it here.
      placeholder: Your uplift configuration
      render: yaml
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Which version?
      description: Which version of uplift are you using? `uplift version --short`
      placeholder: Uplift version
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Which operating system(s) are you using?
      multiple: true
      options:
        - Linux
        - Mac
        - Windows
        - All
    validations:
      required: true
  - type: textarea
    id: debug
    attributes:
      label: Optional debug output
      description: Please provide optional debug output if you think it will help. `uplift bump --verbose`
      render: shell
    validations:
      required: false
