name: Documentation Edit
description: Suggest an edit to the documentation
title: "[Docs]: "
labels: [documentation, triage]
assignees:
  - ga-paul-t
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new documentation edit request. Please be as descriptive and concise as possible. We value all input from the community.
  - type: textarea
    id: describe-edit
    attributes:
      label: Describe your edit
      description: A clear and concise description of the documentation edit you are requesting.
      placeholder: Your edit?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/gembaadvantage/uplift/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
