name: docker-description
on:
  push:
    branches:
      - main
    paths:
      - "README.md"
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.GA_DOCKER_USERNAME }}
          password: ${{ secrets.GA_DOCKER_PASSWORD }}
          repository: "gembaadvantage/uplift"
          short-description: "Semantic versioning the easy way. Powered by Conventional Commits. Built for use with CI"
          readme-filepath: ./README.md
