name: uplift
on:
  workflow_dispatch:

jobs:
  uplift:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_UPLIFT }}

      - name: Release
        uses: gembaadvantage/uplift-action@v2.0.2
        with:
          args: release --skip-changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GH_UPLIFT }}
